---


- name: create certbot dir
  file: "path={{certbot_install_dir}} mode=755 state=directory"

- name: download certbot
  get_url: url="https://dl.eff.org/certbot-auto" dest="{{certbot_install_dir}}/certbot-auto"

- name: make certbot executable
  file: "path={{certbot_install_dir}}/certbot-auto mode=755"

- name: check if cert does exist
  stat: "path={{cert_path}}/cert.pem"
  register: certificate


- name: create cert
  command: "{{certbot_install_dir}}/certbot-auto certonly -n --agree-tos --email {{cert_email}} --standalone -d {{domain}}"
  when: certificate.stat.exists == False

- name: renew cert
  command: "{{certbot_install_dir}}/certbot-auto renew -n --agree-tos --email {{cert_email}} --standalone -d {{domain}}"
  when: certificate.stat.exists == True

- name: download cacerts
  get_url: url="{{item.value.link}}" dest="{{download_dir}}/{{item.value.file}}"
  with_dict: "{{letsencrypt_certs}}"

- name: install cacerts in truststore
  command: "keytool -importcert  -noprompt -storepass {{java_storepass}} -alias {{item.key}} -keystore {{java_install_location}}/jre/lib/security/cacerts --file {{download_dir}}/{{item.value.file}}"
  with_dict: "{{letsencrypt_certs}}"
  ignore_errors: True



